#cloud-config
autoinstall:
  version: 1
  # Autoinstall version to work with Ubuntu Desktop

  interactive-sections:  # Enable Wifi selection and keyboard layout selection
    - keyboard
  storage:  # This should set the interactive (lvm set) default
    layout:
      name: lvm
      sizing-policy: all
      password: jpSC-ek2s5
      match:
        size: largest
  locale: en_US.UTF-8
  timezone: America/Phoenix
  keyboard:
    layout: us
  identity:
    hostname: Ubuntu-Provisioning-Desktop
    realname: "Admin"
    username: admin
    password: '$y$j9T$sV/aEMjzPOqVY6YnHdZbg.$NOpjDzZyKpCqXQidpAxjgC1JpdALSctfRshxpns6912'
  ssh:
    allow-pw: true # false will disable the ability to use password, must use the SSH pair keys
    install-server: true
  apt:
    mirror-selection:
      primary:
        - country-mirror
        - uri: http://archive.ubuntu.com/ubuntu/
    geoip: true
  packages:
    - curl  
  late-commands:
    # Download packages folder
    - mkdir -p /target/var/log/axonit
    - date > /target/var/log/axonit/pre-install.log
    - mkdir -p /target/opt/axonit/packages
    - curl -Lo /target/opt/axonit/packages/axon_diskEncryption.sh 'https://itengineeringtest.blob.core.windows.net/itengineer-test-blob/axon_diskEncryption.sh?sp=r&st=2025-06-05T09:45:22Z&se=2025-07-31T17:45:22Z&sip=27.65.192.78&spr=https&sv=2024-11-04&sr=b&sig=3aaLi71m6cMl6sbGko6tYkSK4CjRlwDMVwkmZlACZ%2Fs%3D'
    #- curl -Lo /target/opt/axonit/
   # - unzip /target/opt/axonit/packages.zip -d /target/opt/axonit/
    - ls -la /target/opt/axonit/ >> /target/var/log/axonit/pre-install.log
    # Hide TI account from login screen
    # Enable This will trigger gnome to prompt to create new local user
    - mkdir -p /target/var/lib/AccountsService/users
    - echo '[User]' > /target/var/lib/AccountsService/users/admin
    - echo 'SystemAccount=true' >> /target/var/lib/AccountsService/users/admin
    - curtin in-target -- hostnamectl set-hostname "LW-VM-$(sudo dmidecode -t system | grep Serial | awk '{print $3}')"
    - umount -lf /cdrom
  # user-data: # Commands here run during first boot (cannot be interactive)
  #   disable_root: false # true: will disable root access
  #   runcmd:
